### PR TITLE
WIP: tl_classifier(Warning: Large file)

### PR DESCRIPTION
**Pull request by toby4548**
I added an inception model trained with Tensorflow object detection API for traffic light classifier.

The model is quite large(~50mb). I included it in the repo because I think we have to submit with the model? Please correct me if I'm wrong. Since it's large, you can also open a new branch for me to merge if you want to keep the master clean. 

It's possible to turn on/off the model with the USE_MODEL parameter.

**For some reason, the model doesn't work at beginning...(maybe depend on the computer?)**
you have to manually move the car a little bit to make it work at the beginning. For the other traffic lights, the model works pretty well. 

Paradeep can update the model later simply by replacing the frozen_graph in the model directory.

Tony

### CODE REVIEW

**Comment by pbanavara** [comment]
Hey @toby4548 I have a frozen_graph.pb which is goddamn 170 MB even after zipping so I have to figure out a way to break it down and check in

**Comment by toby4548** [comment]
How about open a new branch for me to merge. The model here is big but within the size that github can manage. Others can take test with it if they want.

**Comment by pbanavara** [comment]
I have merged this and I have found a way to break the model into chunks. so will checkout and update this branch.

**Comment by pbanavara** [comment]
Sorry I thought I had a branch but have merged this to the master

**Pull request merged**
